export const getHistory = (id) => {
  return historyContainer.get(id);
}

//Modificar esta data para tener la historia de los 3 y agregarles id (quizas investigar como usar un data type Map)
const VIVIENNEWESTWOOD = [
  {
    title: 'Early years',
    paragraph: 'Westwood was born in the village of Tintwistle, Cheshire, on 8 April 1941,as the daughter of Gordon Swire and Dora Swire, who had married two years previously, two weeks after the outbreak of World War II. At the time of Vivienne\'s birth, her father was employed as a storekeeper in an aircraft factory; he had previously worked as a greengrocer\.In 1958, her family moved to Harrow, Middlesex, and Westwood took a jewellery and silversmith course at the University of Westminster, then known as the Harrow Art School, but left after one term, saying: "I didn\'t know how a working-class girl like me could possibly make a living in the art world". After taking up a job in a factory and studying at a teacher-training college, she became a primary school teacher. During this period, she created her own jewellery, which she sold at a stall on Portobello Road\.In 1962, she met Derek Westwood, a Hoover factory apprentice, in Harrow. They married on 21 July 1962; Westwood made her own wedding dress. In 1963, she gave birth to a son, Benjamin Westwood.'
  },
  {
    title: 'Punk era',
    paragraph: 'Westwood was one of the architects of the punk fashion phenomenon of the 1970s, saying "I was messianic about punk, seeing if one could put a spoke in the system in some way".The store that she co-managed with McLaren, SEX, was a meeting place for early members of the London punk scene. Westwood also inspired the style of punk icons, such as Viv Albertine, who wrote in her memoir, "Vivienne and Malcolm use clothes to shock, irritate and provoke a reaction but also to inspire change. Mohair jumpers, knitted on big needles, so loosely that you can see all the way through them, T-shirts slashed and written on by hand, seams and labels on the outside, showing the construction of the piece; these attitudes are reflected in the music we make. It\'s OK to not be perfect, to show the workings of your life and your mind in your songs and your clothes."'
  }
]

const VERSACE = [
  {
    title: 'Atelier Versace',
    paragraph: 'In 1972, Gianni Versace designed his first collections for Callaghan, Genny, and Complice. In 1978, the company launched under the name "Gianni Versace Donna” and opened its first boutique in Milan\'s Via della Spiga. Gianni independently controlled much of the brand, from designing to retailing. In 1982, the company expanded its offerings to include accessories, jewelry, home furnishings, and china. In 1993, Donatella Versace added the Young Versace and Versus lines. In 1994, the brand gained international coverage from the black Versace dress of Elizabeth Hurley, referred in the media \'as "that dress". Versace has designed for various music artists, including stage and album cover costumes for Elton John in 1992 and outfits for Michael Jackson. Versace also designed clothing for the Princess of Wales and Princess Caroline of Monaco.After the murder of Gianni Versace in 1997, his sister Donatella, formerly vice-president, took over as creative director, and his older brother Santo Versace became CEO.Donatella\'s daughter Allegra Versace was left a 50 percent stake in the company, which she assumed control of on her eighteenth birthday. In 2000, the green Versace dress worn by Jennifer Lopez at the Grammy Awards gained extensive media attention. The dress was voted the fifth most iconic dress of all time and Elizabeth Hurley\'s black Versace dress was voted most iconic dress of all time, according to a 2008 Daily Telegraph poll. With the company\'s profits in decline in the early 2000s, Fabio Massimo Cacciatori was hired as interim CEO to reorganise and restructure Versace Group in 2003. Cacciatori resigned in December 2003 due to "disputes with the Versace family". In 2004, Giancarlo di Risio from IT Holding became CEO, until he resigned in 2009 due to disagreements with Donatella. In May 2016, the Versace Group appointed Jonathan Akeroyd as CEO and board member. In February 2014, The Blackstone Group purchased a 20 percent stake in Versace for €210 million. As of 2016, more than 1500 boutiques operate worldwide; the first boutique outside of Italy opened in Glasgow, Scotland, in 1991. In September 2018, Michael Kors offered to buy Versace for two billion euros. Versace announced all Blackstone and Versace family shares were sold to Michael Kors Limited. The acquisition was completed in December 2018, with Donatella Versace remaining head of creative design. In January 2019, Gianni Versace S.r.l. joined Capri Holdings Limited, forming a new global fashion luxury group alongside Michael Kors and Jimmy Choo. In 2018, Versace stopped using fur in its products and in 2020 announced it would stop using kangaroo leather. In October 2018, Versace announced its first Pre-Fall season show in New York, scheduled on Gianni Versace\'s December 2 birth date. In 2021, Versace opened its first SoHo, New York boutique.'
  },
]

const YOHIJIYAMAMOTO = [
  {
    title: 'Early life',
    paragraph: 'Born in Tokyo, Yamamoto graduated from Keio University with a degree in law in 1966. He gave up a prospective legal career to assist his mother in her dressmaking business, from where he learned his tailoring skills.He further studied fashion design at Bunka Fashion College, getting a degree in 1969.'
  },
  {
    title: 'Career',
    paragraph: 'Yamamoto debuted in Tokyo in 1977, followed by two more shows; a debut in Paris in 1981 and in New York in 1982.[7] His first collection under the label Y\'s, focused on a collection for women that reflected typical men\'s garments, with clothes cut in uncluttered shapes with washed fabrics and dark colors.[8] In an interview with The New York Times in 1983, Yamamoto said of his designs, "I think that my men\'s clothes look as good on women as my women\'s clothing […] When I started designing, I wanted to make men\'s clothes for women." More recently he has expounded: "When I started making clothes for my line Y\'s in 1977, all I wanted was for women to wear men\'s clothes. I jumped on the idea of designing coats for women. It meant something to me – the idea of a coat guarding and hiding a woman\'s body. I wanted to protect the woman\'s body from something – maybe from men\'s eyes or a cold wind."His commercially successful main line, Yohji Yamamoto (women/men) and Y\'s, are especially popular in Tokyo. These two lines are also available at his flagship stores in Paris and Antwerp, and at high-end department stores worldwide. Other principal lines include Pour Homme, Costume d\'Homme, and the diffusion line Coming Soon. Yohji Yamamoto Inc. reported in 2007 that the sales of Yamamoto\'s two main lines average above $100 million annually.Yamamoto is known for an avant-garde spirit in his clothing, frequently creating designs far removed from current trends. His signature oversized silhouettes often feature drapery in varying textures. Yohji\' collections are predominately made in black, a colour which Yamamoto has described as "modest and arrogant at the same time. Black is lazy and easy – but mysterious. But above all black says this: "I don\'t bother you – don\'t bother me". Poor decisions by finance managers pushed the brand into debts of more than US$65 million in 2009, which angered Yamamoto and led to a company restructuring from 2009 to 2010. The private equity firm Integral Corp was identified as the Japanese company who will restructure the Yohji Yamamoto Inc and by November 2010 the company was out of debt and avoiding the risk of bankruptcy.'
  },
  {
    title: 'Fashion advocacy',
    paragraph: 'In 2008, the Yohji Yamamoto Fund for Peace was established to foster development of China\'s fashion industry and to help heal the long-standing enmity between China and Japan. Each year, an emerging Chinese designer will be awarded with a two-year scholarship to a fashion college in Japan or Europe, and a male or female Chinese fashion model will be selected to make a runway debut during the Paris prêt-à-porter season.Yamamoto has been quoted as saying: "they must have so many angry young people. Being a fashion designer or an artist, you have to be angry."[14] Of the fashion show he staged in Beijing in spring 2008 to launch this initiative, Yamamoto said, "It\'s not political. I am going to open a store here, then Chinese people will come and shop there, and then they are happy. The real art is making people happy, but also asking questions about society."'
  },
]

const historyContainer = new Map ([
  ['0',VERSACE],
  ['1',VIVIENNEWESTWOOD],
  ['2',YOHIJIYAMAMOTO],
])